version: "3.9"
services:
  db:
    image: postgres
    container_name: seguridad-redes-db
    networks:
      - seg-redes
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: seguridad-redes-api
    env_file:
      - ./api/.env
    networks:
      - seg-redes
    volumes:
      - ./api:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: seguridad-redes-app
    env_file:
      - ./app/.env
    networks:
      - seg-redes
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:

networks:
  seg-redes:
    name: seg-redes
